### ISSUE TITLE
Missing html file in npm release

### ISSUE THREAD

**Issue by alappe** [apache/couchdb-fauxton#1275]
I just updated our fauxton sidecar containers and noticed that it's not working for me. Simplified, this is what I do:

```
$ cd /tmp
$ npm install fauxton@1.2.4
$ ./node_modules/fauxton/bin/fauxton
$ curl localhost:8000
{"error":"ENOENT: no such file or directory, stat '/private/tmp/node_modules/fauxton/dist/release/index.html'"}
```

Same happens in `master` for me. 

## Expected Behavior

A working fauxton.

## Your Environment

- fauxton 1.2.4 from npm and github.
- node v12.16.1
- npm 6.13.4

**Comment by popojargo** [comment]
@Antonio-Maranhao What's the proper way to make a release? I think I skipped a few steps when I released. We could also make those instructions part or a [prepublishOnly](https://docs.npmjs.com/misc/scripts#prepublish-and-prepare) hook.

**Comment by alappe** [comment]
👍

I also tried `npm run webpack:release`, hoping that I could do a local release myself, but this failed with another error.

**Comment by popojargo** [comment]
I suspect it's `grunt couchdb` but I would like a confirmation before creating another release

**Comment by Antonio-Maranhao** [comment]
@popojargo I haven't done it either. At most, I've only created the git tag, but that's it.
Maybe @garrensmith knows

**Comment by MussaratAziz** [comment]
Still not fixed i am getting same error as mentioned by @alappe ..

**Comment by popojargo** [comment]
@MussaratAziz @alappe Can you try the version 1.25?

**Comment by alappe** [comment]
@popojargo `v1.2.5` works for me—thank you!
